import React, { useState } from 'react';
import {
  Box,
  Typography,
  Button,
  Paper,
  Grid,
  Card,
  CardContent,
  Alert,
  IconButton,
  Tooltip,
  Chip,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField
} from '@mui/material';
import {
  Download,
  Share,
  Print,
  CheckCircle,
  Description,
  Analytics,
  ContentCopy,
  ThumbUp,
  ThumbDown
} from '@mui/icons-material';
import { submitFeedback } from '../services/api';

const ProtocolSummary = ({ summary, sections }) => {
  const [copied, setCopied] = useState(false);
  const [userSession] = useState(() => `summary_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`);
  const [actionFeedback, setActionFeedback] = useState({});
  const [disapprovalDialogOpen, setDisapprovalDialogOpen] = useState(false);
  const [disapprovalReason, setDisapprovalReason] = useState('');
  const [approvalStatus, setApprovalStatus] = useState(null);
  const [summaryId] = useState(() => `summary_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`);

  const handleDownloadSummary = async () => {
    if (!summary) return;
    
    const element = document.createElement('a');
    const file = new Blob([summary], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `clinical-protocol-summary-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    // Record feedback
    try {
      await submitFeedback({
        message_id: `download_${Date.now()}`,
        question: 'Download summary',
        answer: summary,
        reaction_type: 'download_summary',
        user_session: userSession,
        sources: [],
        evidence_count: 0,
        confidence_score: 1.0,
        additional_data: {
          summary_length: summary.length,
          sections_count: sections?.length || 0
        }
      });
      
      // Show feedback
      setActionFeedback(prev => ({ ...prev, download: true }));
      setTimeout(() => setActionFeedback(prev => ({ ...prev, download: false })), 2000);
    } catch (error) {
      console.error('Failed to record download feedback:', error);
    }
  };

  const handleCopySummary = async () => {
    if (!summary) return;
    
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      
      // Record feedback
      await submitFeedback({
        message_id: `copy_summary_${Date.now()}`,
        question: 'Copy summary',
        answer: summary,
        reaction_type: 'copy_summary',
        user_session: userSession,
        sources: [],
        evidence_count: 0,
        confidence_score: 1.0,
        additional_data: {
          summary_length: summary.length,
          sections_count: sections?.length || 0
        }
      });
    } catch (error) {
      console.error('Failed to copy or record feedback:', error);
    }
  };

  const handlePrintSummary = async () => {
    if (!summary) return;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Clinical Protocol Summary</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
            .header { margin-bottom: 30px; }
            .content { white-space: pre-wrap; }
            .footer { margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Clinical Protocol Executive Summary</h1>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
          </div>
          <div class="content">${summary}</div>
          <div class="footer">
            <p>Generated by Clinical Protocol AI Assistant</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
    
    // Record feedback
    try {
      await submitFeedback({
        message_id: `print_${Date.now()}`,
        question: 'Print summary',
        answer: summary,
        reaction_type: 'print_summary',
        user_session: userSession,
        sources: [],
        evidence_count: 0,
        confidence_score: 1.0,
        additional_data: {
          summary_length: summary.length,
          sections_count: sections?.length || 0
        }
      });
      
      // Show feedback
      setActionFeedback(prev => ({ ...prev, print: true }));
      setTimeout(() => setActionFeedback(prev => ({ ...prev, print: false })), 2000);
    } catch (error) {
      console.error('Failed to record print feedback:', error);
    }
  };

  const handleApproveSummary = async () => {
    try {
      const response = await fetch('http://localhost:8001/summary-approval', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          summary_id: summaryId,
          status: 'approved',
          user_session: userSession,
          summary_content: summary,
          approved_sections_count: sections?.filter(s => s.approved).length || 0
        })
      });

      if (response.ok) {
        setApprovalStatus('approved');
        setActionFeedback(prev => ({ ...prev, approve: true }));
        setTimeout(() => setActionFeedback(prev => ({ ...prev, approve: false })), 2000);
      }
    } catch (error) {
      console.error('Failed to record approval:', error);
    }
  };

  const handleDisapproveSummary = () => {
    setDisapprovalDialogOpen(true);
  };

  const handleSubmitDisapproval = async () => {
    if (!disapprovalReason.trim()) {
      alert('Please provide a reason for disapproval');
      return;
    }

    try {
      const response = await fetch('http://localhost:8001/summary-approval', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          summary_id: summaryId,
          status: 'disapproved',
          reason: disapprovalReason,
          user_session: userSession,
          summary_content: summary,
          approved_sections_count: sections?.filter(s => s.approved).length || 0
        })
      });

      if (response.ok) {
        setApprovalStatus('disapproved');
        setDisapprovalDialogOpen(false);
        setDisapprovalReason('');
        setActionFeedback(prev => ({ ...prev, disapprove: true }));
        setTimeout(() => setActionFeedback(prev => ({ ...prev, disapprove: false })), 2000);
      }
    } catch (error) {
      console.error('Failed to record disapproval:', error);
    }
  };

  const approvedSections = sections?.filter(section => section.approved) || [];
  const totalSections = sections?.length || 0;

  return (
    <Box sx={{ 
      display: 'flex', 
      flexDirection: 'column',
      minHeight: '100vh'
    }}>
      {/* Header */}
      <Box sx={{ p: 3, borderBottom: 1, borderColor: 'divider', flexShrink: 0 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box>
            <Typography variant="h5" gutterBottom>
              Protocol Summary
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Executive summary and key insights from your clinical protocol
            </Typography>
          </Box>
          
          {summary && (
            <Box sx={{ display: 'flex', gap: 1 }}>
              <Tooltip title={copied ? "Copied!" : "Copy summary"}>
                <IconButton 
                  onClick={handleCopySummary}
                  color={copied ? "success" : "default"}
                >
                  <ContentCopy />
                </IconButton>
              </Tooltip>
              <Tooltip title={actionFeedback.print ? "Printed!" : "Print summary"}>
                <IconButton 
                  onClick={handlePrintSummary}
                  color={actionFeedback.print ? "success" : "default"}
                >
                  <Print />
                </IconButton>
              </Tooltip>
              <Button
                variant="contained"
                startIcon={<Download />}
                onClick={handleDownloadSummary}
                color={actionFeedback.download ? "success" : "primary"}
              >
                {actionFeedback.download ? "Downloaded!" : "Download"}
              </Button>
            </Box>
          )}
        </Box>
      </Box>

      <Box sx={{ 
        flex: 1, 
        p: 3,
        minHeight: 0
      }}>
        {/* Summary Stats */}
        {sections && sections.length > 0 && (
          <Paper sx={{ p: 3, mb: 3 }}>
            <Typography variant="h6" gutterBottom>
              Summary Statistics
            </Typography>
            <Grid container spacing={3}>
              <Grid item xs={12} sm={3}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h4" color="primary.main" fontWeight="bold">
                    {totalSections}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Total Sections
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={3}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h4" color="success.main" fontWeight="bold">
                    {approvedSections.length}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Approved Sections
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={3}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h4" color="info.main" fontWeight="bold">
                    {summary ? Math.round(summary.split(' ').length) : 0}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Summary Words
                  </Typography>
                </Box>
              </Grid>
              <Grid item xs={12} sm={3}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography variant="h4" color="warning.main" fontWeight="bold">
                    {sections ? Math.round((sections.reduce((sum, s) => sum + s.confidence, 0) / sections.length) * 100) : 0}%
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Avg. Confidence
                  </Typography>
                </Box>
              </Grid>
            </Grid>
          </Paper>
        )}

        {/* Executive Summary */}
        {summary ? (
          <Paper sx={{ mb: 3 }}>
            <Box sx={{ p: 3, borderBottom: 1, borderColor: 'divider' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, justifyContent: 'space-between' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <Description color="primary" />
                  <Typography variant="h6">
                    Executive Summary
                  </Typography>
                  <Chip label="AI Generated" size="small" color="primary" variant="outlined" />
                </Box>
                {approvalStatus && (
                  <Chip 
                    label={approvalStatus === 'approved' ? 'Approved ✓' : 'Disapproved ✗'} 
                    color={approvalStatus === 'approved' ? 'success' : 'error'}
                    variant="filled"
                  />
                )}
              </Box>
            </Box>
            <Box sx={{ p: 3 }}>
              <Typography 
                variant="body1" 
                sx={{ 
                  whiteSpace: 'pre-wrap',
                  lineHeight: 1.7,
                  fontSize: '1.1rem',
                  mb: 3
                }}
              >
                {summary}
              </Typography>
              
              {/* Approval Buttons */}
              <Box sx={{ display: 'flex', gap: 2, pt: 2, borderTop: 1, borderColor: 'divider' }}>
                <Button
                  variant={approvalStatus === 'approved' ? 'contained' : 'outlined'}
                  color="success"
                  startIcon={<ThumbUp />}
                  onClick={handleApproveSummary}
                  disabled={approvalStatus === 'approved'}
                >
                  {approvalStatus === 'approved' ? 'Approved' : 'Approve Summary'}
                </Button>
                <Button
                  variant={approvalStatus === 'disapproved' ? 'contained' : 'outlined'}
                  color="error"
                  startIcon={<ThumbDown />}
                  onClick={handleDisapproveSummary}
                  disabled={approvalStatus === 'disapproved'}
                >
                  {approvalStatus === 'disapproved' ? 'Disapproved' : 'Disapprove Summary'}
                </Button>
              </Box>
            </Box>
          </Paper>
        ) : (
          <Alert severity="info" sx={{ mb: 3 }}>
            <Typography variant="body1" gutterBottom>
              No summary available yet
            </Typography>
            <Typography variant="body2">
              To generate an executive summary:
            </Typography>
            <List dense>
              <ListItem>
                <ListItemText primary="1. Go to Document Analysis tab" />
              </ListItem>
              <ListItem>
                <ListItemText primary="2. Extract key sections from your protocol" />
              </ListItem>
              <ListItem>
                <ListItemText primary="3. Review and approve relevant sections" />
              </ListItem>
              <ListItem>
                <ListItemText primary="4. Generate the executive summary" />
              </ListItem>
            </List>
          </Alert>
        )}

        {/* Approved Sections Overview */}
        {approvedSections.length > 0 && (
          <Paper sx={{ mb: 3 }}>
            <Box sx={{ p: 3, borderBottom: 1, borderColor: 'divider' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Analytics color="success" />
                <Typography variant="h6">
                  Approved Sections ({approvedSections.length})
                </Typography>
              </Box>
            </Box>
            <Box sx={{ p: 3 }}>
              <Grid container spacing={2}>
                {approvedSections.map((section, index) => (
                  <Grid item xs={12} sm={6} md={4} key={index}>
                    <Card variant="outlined" sx={{ height: '100%' }}>
                      <CardContent>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                          <CheckCircle color="success" fontSize="small" />
                          <Typography variant="subtitle2" fontWeight="bold">
                            {section.title}
                          </Typography>
                        </Box>
                        <Typography variant="body2" color="text.secondary" gutterBottom>
                          {section.description}
                        </Typography>
                        <Chip
                          label={`${Math.round(section.confidence * 100)}% confidence`}
                          size="small"
                          color={section.confidence >= 0.8 ? 'success' : section.confidence >= 0.6 ? 'warning' : 'error'}
                        />
                      </CardContent>
                    </Card>
                  </Grid>
                ))}
              </Grid>
            </Box>
          </Paper>
        )}

        {/* Usage Guidelines */}
        <Paper sx={{ p: 3, backgroundColor: 'grey.50' }}>
          <Typography variant="h6" gutterBottom>
            Next Steps
          </Typography>
          <List>
            <ListItem>
              <ListItemIcon>
                <Share color="primary" />
              </ListItemIcon>
              <ListItemText 
                primary="Share with Team" 
                secondary="Download or print the summary to share with your research team"
              />
            </ListItem>
            <ListItem>
              <ListItemIcon>
                <Analytics color="primary" />
              </ListItemIcon>
              <ListItemText 
                primary="Regulatory Review" 
                secondary="Use this summary for regulatory submissions and stakeholder presentations"
              />
            </ListItem>
            <ListItem>
              <ListItemIcon>
                <Description color="primary" />
              </ListItemIcon>
              <ListItemText 
                primary="Documentation" 
                secondary="Include in study documentation and protocol amendments"
              />
            </ListItem>
          </List>
        </Paper>
      </Box>

      {/* Disapproval Reason Dialog */}
      <Dialog 
        open={disapprovalDialogOpen} 
        onClose={() => setDisapprovalDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>
          Why are you disapproving this summary?
        </DialogTitle>
        <DialogContent sx={{ pt: 2 }}>
          <TextField
            fullWidth
            multiline
            rows={4}
            placeholder="Please provide a reason for disapproving this summary (e.g., missing information, inaccurate content, poor organization, etc.)"
            value={disapprovalReason}
            onChange={(e) => setDisapprovalReason(e.target.value)}
            variant="outlined"
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDisapprovalDialogOpen(false)}>
            Cancel
          </Button>
          <Button 
            onClick={handleSubmitDisapproval}
            variant="contained"
            color="error"
            disabled={!disapprovalReason.trim()}
          >
            Submit Disapproval
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default ProtocolSummary;